export const keys = [
  
  { en: "~", ru: "Ё", code: "Backquote" },
  { en: "1", ru: "1", code: "Digit1" },
  { en: "2", ru: "", code: "Digit2" },
  { en: "3", ru: "", code: "Digit3" },
  { en: "4", ru: "", code: "Digit4" },
  { en: "5", ru: "", code: "Digit5" },
  { en: "6", ru: "", code: "Digit6" },
  { en: "7", ru: "", code: "Digit7" },
  { en: "8", ru: "", code: "Digit8" },
  { en: "9", ru: "", code: "Digit9" },
  { en: "0", ru: "", code: "Digit0" },
  { en: "-", ru: "", code: "Minus" },
  { en: "=", ru: "", code: "Equal" },
  { en: "BackSpace", ru: "BackSpace", code: "Backspace", type: 'big' },
  { en: "Tab", ru: "Tab", code: "Tab", type: 'big' },
  { en: "q", ru: "й", code: "KeyQ" },
  { en: "w", ru: "ц", code: "KeyW" },
  { en: "e", ru: "у", code: "KeyE" },
  { en: "r", ru: "к", code: "KeyR" },
  { en: "t", ru: "е", code: "KeyT" },
  { en: "y", ru: "н", code: "KeyY" },
  { en: "u", ru: "г", code: "KeyU" },
  { en: "i", ru: "ш", code: "KeyI" },
  { en: "o", ru: "щ", code: "KeyO" },
  { en: "p", ru: "з", code: "KeyP" },
  { en: "[", ru: "х", code: "BracketLeft" },
  { en: "]", ru: "ъ", code: "BracketRight" },
  { en: "Del", ru: "Del", code: "Delete" },
  { en: "CapsLock", ru: "CapsLock", code: "CapsLock", type: 'big' },
  { en: "a", ru: "ф", code: "KeyA" },
  { en: "s", ru: "ы", code: "KeyS" },
  { en: "d", ru: "в", code: "KeyD" },
  { en: "f", ru: "а", code: "KeyF" },
  { en: "g", ru: "п", code: "KeyG" },
  { en: "h", ru: "р", code: "KeyH" },
  { en: "j", ru: "о", code: "KeyJ" },
  { en: "k", ru: "л", code: "KeyK" },
  { en: "l", ru: "д", code: "KeyL" },
  { en: ";", ru: "ж", code: "Semicolon" },
  { en: "'", ru: "э", code: "Quote" },
  { en: "Enter", ru: "Enter", code: "Enter", type: 'big' },
  { en: "Shift", ru: "Shift", code: "ShiftLeft", type: 'big' },
  { en: "z", ru: "я", code: "KeyZ" },
  { en: "x", ru: "ч", code: "KeyX" },
  { en: "c", ru: "с", code: "KeyC" },
  { en: "v", ru: "м", code: "KeyV" },
  { en: "b", ru: "и", code: "KeyB" },
  { en: "n", ru: "т", code: "KeyN" },
  { en: "m", ru: "ь", code: "KeyM" },
  { en: "/", ru: "/", code: "KeyM" },
  { en: "<", ru: "б", code: "Comma" },
  { en: ">", ru: "ю", code: "Period" },
  { en: "↑", ru: "↑", code: "ArrowUp" },
  { en: "Shift", ru: "Shift", code: "ShiftRight", type: 'big' },
  { en: "Ctrl", ru: "Ctrl", code: "ControlLeft", type: 'not' },
  { en: "Win", ru: "Win", code: "MetaRight", type: 'not' },
  { en: "Alt", ru: "Alt", code: "AltLeft", type: 'not' },
  { en: "SPACE", ru: "SPACE", code: "Space", type: 'extrabig' },
  { en: "Alt", ru: "Alt", code: "AltRight", type: 'not' },
  { en: "←", ru: "←", code: "ArrowLeft" },
  { en: "↓", ru: "↓", code: "ArrowDown" },
  { en: "→", ru: "→", code: "ArrowRight" },
  { en: "Ctrl", ru: "Ctrl", code: "ControlRight", type: 'not' },
];
